-- Deprecated dummy seed.
-- Use docs/week2/B-5_seed_likelion_university_data.sql instead.
--
-- B-5 replaces existing rows where school.is_seeded=true with:
-- - 80 LikeLion university schools
-- - 5,266 AcademyInfo department rows matched to those schools
